get:
  tags:
    - Product Master
  summary: List of Product Master
  description: Returns a list of product master by filter
  operationId: getProductMasters
  parameters:
    - name: skip
      in: query
      description: Limit number of return items
      required: false
      style: form
      schema:
        type: integer
        format: int64
    - name: limit
      in: query
      description: Limit number of return items
      required: false
      style: form
      schema:
        type: integer
        format: int64
  security:
    - api_key: []
