openapi: 3.0.2
info:
  version: 1.0.1
  title: Central Bridge
  termsOfService: "https://example.com/terms/"
  contact:
    email: contact@seac.com
    url: "https://www.seasiacenter.com/"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "./SEAC.png"
  description: >
    # Introduction

    Central Bridge API is built on HTTP. Our API is RESTful. 
    It has predictable resource URLs. It returns HTTP response codes to indicate errors. 
    It also accepts and returns JSON in the HTTP body. 
    You can use your favorite HTTP/REST library for your programming language to use Central Bridge's API.

    # Authentication

    To access each APIs, user have to add `x-ar-token` in headers for the authorization. 
    Authentication for Central Bridge is based on [key-auth](https://en.wikipedia.org/wiki/Key_authentication).

externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
tags:
  # - name: Echo
  #   description: Example echo operations
  # - name: User
  #   description: Operations about user
  - name: Product Master
    description: Information of Product Master
  - name: Coupon Master
    description: Information of Coupon Master
  - name: Webhook
    description: Receive real-time data from AR modules
  - name: Connection
    description: For Testing Connection
x-tagGroups:
  - name: General
    tags:
      - Connection
      - Webhook
  - name: AR API
    tags:
      - Product Master
      - Coupon Master
servers:
  - url: "https://central-bridge.vercel.app/api/"
    description: Central dev server
  - url: "http://ar-dev.seac.com/api/v1"
    description: AR dev server
paths:
  # "/users/{username}":
  #   $ref: "paths/users@{username}.yaml"
  # /echo:
  #   $ref: paths/echo.yaml
  /ping:
    $ref: paths/ping.yaml
  /coupons:
    $ref: paths/coupons.yaml
  /coupons/{id}:
    $ref: paths/coupons@{id}.yaml
  /coupons/{id}/_reserve:
    $ref: paths/coupons@{id}@_reserve.yaml
  /products:
    $ref: paths/products.yaml
  /products/{sku}:
    $ref: paths/products@{sku}.yaml
  /webhook:
    $ref: paths/webhook.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-ar-token
